In [2]:
# Q.1-Create a null vector of size 10 but the fifth value which is 1.
import numpy as np 
vector=np.zeros(10)
vector[4]=1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
#Q.2-Create a vector with values ranging from 10 to 49.
import numpy as np
vector=np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
#Q.3-Create a 3x3 matrix with values ranging from 0 to 8.
import numpy as np

matrix=np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [1]:
#Q.4-Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
array = np.array([1, 2, 0, 0, 4, 0])
x = np.nonzero(array)
print("non-zero elements:", x)

non-zero elements: (array([0, 1, 4], dtype=int64),)


In [19]:
#Q.5-Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np 
array=np.random.rand(10,10)
min_value = array.min()
max_value = array.max()
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.0005591733881321614
Maximum value: 0.9875118064966925


In [22]:
#Q.6-Create a random vector of size 30 and find the mean value.
import numpy as np
vector=np.random.rand(30)
mean=vector.mean()
print("mean value :",mean)

mean value : 0.5825132137934133
